language: cpp

branches:
  only:
    - gh-pages
    - master
    - CI-implementation

matrix:
  include:
    - os: osx
      osx_image: xcode11.6
      addons:
        homebrew:
          packages:
            - doxygen

dist: trusty

before_install:
  - chmod +x ./.travis/install.sh
  -
install:
  - ./.travis/install.sh

before_script:
  - g++ --version
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script:
  - cd build
  - cmake -DBUILD_DOCUMENTATION=ON ..
  - ctest
