language: cpp

branches:
  only:
    - gh-pages
    - master
    - CI-implementation

matrix:
  include:
    - os: osx
      python: 3.7
      osx_image: xcode11.6
      addons:
        homebrew:
          packages:
            - doxygen

dist: trusty

before_install:
  - chmod +x ./.travis/install.sh
  - python3 --version
  - pip3 install sphinx_rtd_theme
  - pip3 install breathe

install:
  - ./.travis/install.sh

before_script:
  - g++ --version
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script:
  - cd build
  - cmake -DBUILD_DOCUMENTATION=ON ..
  - make
  - ctest
